apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: t6rhr7wtf-go 
  janus-idp.io/tekton: t6rhr7wtf-go
  backstage.io/kubernetes-id: t6rhr7wtf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t6rhr7wtf-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml