apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: t6rhr7wtf-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: t6rhr7wtf-go 
  name: t6rhr7wtf-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: t6rhr7wtf-go 
